# -*- coding: utf-8 -*-
"""Laurie  Streamlit : build and share data apps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rJIOKdcvyZM19FZBy46Wbg0-1WAs3ZC9
"""

!pip install -q streamlit

import streamlit as st
import pandas as pd

st.title('Hello Wilders, welcome to my application!')

st.write("I enjoy to discover stremalit possibilities")

link = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/weather2019.csv"
df_weather = pd.read_csv(link)
st.write(df_weather)