# -*- coding: utf-8 -*-
"""Laurie  Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rJIOKdcvyZM19FZBy46Wbg0-1WAs3ZC9
"""

import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

st.title('Hello Wilders, welcome to my application!')

link = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv"
df = pd.read_csv(link)
st.write(df)

const = st.radio("Continent of analysis", ["US.", "Japan.", "Europe."])

st.title('Analyse de corrélation')
st.pyplot(sns.heatmap(df.corr(), center=0,cmap = sns.color_palette("vlag", as_cmap=True)).figure)

st.title('Analyse MPG')
st.bar_chart(df[df["continent"]==const], x="year", y="mpg")

st.title('Analyse HP')
st.bar_chart(df[df["continent"]==const], x="year", y="hp")