# -*- coding: utf-8 -*-
"""Laurie Streamlit : build and share data apps (lolo10).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rJIOKdcvyZM19FZBy46Wbg0-1WAs3ZC9
"""

import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

st.title('Hello, welcome to my application!')

link = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv"
df = pd.read_csv(link)
st.write("La Base de données des voitures:", df.head())

cont = st.sidebar.radio("Continent of analysis", df["continent"].unique())
filtered_df = df[df["continent"] == cont]
st.title('Analyse mpg')
st.bar_chart(filtered_df, x="year", y="mpg")

st.title('Analyse de corrélation')
st.pyplot(sns.heatmap(df.corr(), center=0,cmap = sns.color_palette("vlag", as_cmap=True)).figure)

st.title("Titanic movie")
st.image("https://drive.google.com/file/d/1iH8ImKKlLkc_UTYBqxdJS-1RxEqkcSRy/view?usp=drive_link", caption="Titanic")

#st.image("https://drive.google.com/uc?export=view&id=1iH8ImKKlLkc_UTYBqxdJS-1RxEqkcSRy", caption='titanic')